server {
    listen 8000;

    location /php/ {
        proxy_pass http://php:8001/;
    }

    location /node/ {
        proxy_pass http://node:8002/;
    }

    location /python/ {
        proxy_pass http://python:8003/;
    }
}
